### ISSUE TITLE
[1.20.1] BrandonsCore integration

### ISSUE THREAD

**Issue by coaber** [FiniteReality/embeddium#140]
### Bug Description

I've noticed that when Draconic Evolution and Embeddium is installed, certain parts of DE's multiblocks (the Draconic Reactor in particular) do not render properly(the reactor core is fully invisible). This is a recurring issue with Rubidium as well, and apparently it has been fixed on a dev branch for 1.18, but never released. [This](https://github.com/Asek3/Rubidium/issues/424) is the issue i posted on rubidium's repo and additionally on their discord support ticket until something was done, apparently it has to do with the rendering library that DE uses, which is CCL. 

### Reproduction Steps

Have the latest DE/CCL/BC and Embeddium installed on the latest 1.18 branch, on FML 40.2.0, then just run them, issue is persistent no matter how you tweak the video settings, and only ceases when embeddium is removed.

### Log File

[latest.log](https://github.com/embeddedt/embeddium/files/13652605/latest.log)

**Comment by embeddedt** [comment]
Thanks for the report. I looked into it, and it's different from the existing CCL compatibility problems (which are already fixed in Embeddium for 1.18). It turns out that the 1.18 version of DE uses a different mechanism to render the reactor core than 1.16, and the approach it uses cannot work properly with Embeddium without being patched. I opened an issue on their end to track this: https://github.com/Draconic-Inc/BrandonsCore/issues/112

If they don't fix their code, I may provide a patch in Embeddium for this later, but no guarantees.

**Comment by FoxMcloud5655** [comment]
We'll look into this and see what's feasible.

**Comment by embeddedt** [comment]
Now that mod compatibility logic is properly separated from the main renderer, it is feasible to apply a patch to BrandonsCore at runtime to resolve this issue. This should be done soon, since 1.18 will likely stop receiving Embeddium updates in the near future.

**Comment by embeddedt** [comment]
This should be fixed in 0.3.2.

**Comment by coaber** [comment]
I'm re-opening this thread again, the issue persists on the latest 1.20.1 branch of DE which is currently in testing phase but i'm being told it's due to the fact that the patches may not applied on embeddium 0.3.19 and up.

**Comment by FoxMcloud5655** [comment]
I said that it could be, not that it was.  I don't know the state of Embeddium on Minecraft 1.20.1 all that well, but DE is now in closed testing and the issue does persist.

You can obtain a copy of the latest version on Brandon's discord, or if that's too much trouble, it can wait until the official release of DE.

**Comment by embeddedt** [comment]
For 1.20.1 it would be ideal for the issue to be fixed more properly on BrandonsCore's end using the approach I suggested in https://github.com/Draconic-Inc/BrandonsCore/issues/112.

**Comment by FoxMcloud5655** [comment]
I'll bring it up to Brandon, then.

**Comment by TedTheTeddo** [comment]
Can confirm this is still an issue that is happening on 1.20.1 with embeddium conflict.

**Comment by embeddedt** [comment]
This will be fixed for 1.20.1 in the next release, by request.

![2024-07-02_19 22 12](https://github.com/embeddedt/embeddium/assets/42941056/a43e4883-c951-4ad3-a325-2ef7c5bbf396)

**Comment by JohnathanFlake** [comment]
Hey i feel bad for asking.

I am bound to 1.18.2. I guess there is no possible way in fixing this issue right?

**Comment by embeddedt** [comment]
@JohnathanFlake The issue should have already been patched in 0.3.2 and newer on 1.18.2.

Realized this issue is still open; going to close it, as the 1.20.1 patch has now also been released.

**Comment by JohnathanFlake** [comment]
Sorry, jokes on me used it, with another Extra Mod for Embeddium/Rubidium. 

It works. Sorry for bothering
